version: "3.8"
services:
  spe_db:
    image: mysql:latest
    restart: unless-stopped
#    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "spe_database"
    ports:
      - "3307:3306"
    volumes:
      - /SPE/:/var/lib/mysql
    networks:
      spe_network:
#        ipv4_address: 172.16.130.6

  spe_backend:
    image: iamosl/spe_server
    depends_on:
      - "spe_db"
#    build:
    restart: on-failure
#    env_file: ./.env
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://spe_db:3306/spe_database?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
#    volumes:
#      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      spe_network:
#        ipv4_address: 172.16.130.7
volumes:
  db:

networks:
  spe_network:
